IF
HPPercentLT(Myself,20)
Global("FHLTigChange","LOCALS",0)
!Dead("FHLXAV")
THEN
RESPONSE #100
SetGlobal("FHLTigChange","LOCALS",1)
SetGlobalTimer("FHLMiettaChange","GLOBAL",90)
ApplySpellRES("FHLMIET",MYSELF)
END

IF
Global("FHLTigChange","LOCALS",1)
GlobalTimerExpired("FHLMiettaChange","GLOBAL")
THEN
RESPONSE #100
SetGlobal("FHLTigChange","LOCALS",0)
ApplySpellRES("FHL491",MYSELF)
END

IF
Global("FHLMDP","GLOBAL",1)
THEN
RESPONSE #100
Panic()
END
