/* ============================================== *
 *         MAIN   COMPONENT  INSTALLATION         *
 * ============================================== */

SILENT

/* -------------------------------------------------------------------------------------------------- *
 *     Adds CamDawg's custom IsValidForPartyDialogue state used throughout the mod. Thanks Cam!       *
 * -------------------------------------------------------------------------------------------------- *
 *  covers STATE_CONFUSED, STATE_FEEBLEMINDED, STATE_SILENCED, STATE_DEAD, STATE_ACID_DEATH,          *
 *  STATE_FLAME_DEATH, STATE_EXPLODING_DEATH, STATE_STONE_DEATH, STATE_FROZEN_DEATH, STATE_HELPLESS,  *
 *  STATE_STUNNED, STATE_PANIC, STATE_BERSERK, STATE_SLEEPING                                         *
 * -------------------------------------------------------------------------------------------------- */
APPEND ~STATE.IDS~ ~0x80101FEF CD_STATE_NOTVALID~ UNLESS ~CD_STATE_NOTVALID~


/* ---------------------------- *
 *  Fixing Imoen's banter file  *
 * ---------------------------- */

// Add Imoen's banter file if Fixpack isn't installed
// --------------------------------------------------
ACTION_IF NOT FILE_EXISTS_IN_GAME ~cdbehbla.pro~ BEGIN
	ACTION_IF (is_tob OR is_ee) BEGIN 
		COPY_EXISTING ~interdia.2da~ ~override~
			SET_2DA_ENTRY 17 1 2 ~BIMOEN2~ // fixes ToB version
		BUT_ONLY
	END ELSE BEGIN
		APPEND ~interdia.2da~ ~IMOEN       BIMOEN2~ UNLESS ~[ %TAB%]BIMOEN2[ %TAB%%LNL%%MNL%%WNL%]~ // fixes SoA version
	END
END

// Gives Imoen a banter file if there isn't one already
// ----------------------------------------------------
ACTION_IF NOT FILE_EXISTS_IN_GAME ~bimoen2.dlg~ BEGIN
	<<<<<<<< luxleysoa/dialogues/bimoen2.d
  BEGIN BIMOEN2
>>>>>>>>
	COMPILE ~luxleysoa/dialogues/bimoen2.d~
END


/* ------------------------------------------ *
 *  Fixing .ids, courtesy of the BG2 Fixpack  *
 * ------------------------------------------ */

// Adds ToB trigger/actions to SoA
// -------------------------------
INCLUDE ~%MOD_FOLDER%/lib/tob2soa.tph~

// Adds timers entry in gtimes.ids
// -------------------------------
INCLUDE ~%MOD_FOLDER%/lib/ids_entries_gtimes.tph~

// Adds kit.ids fixer for classical games
// --------------------------------------
ACTION_IF NOT (is_ee) BEGIN
	INCLUDE ~%MOD_FOLDER%/lib/kit_ids_fixer.tpa~
END



// Copying custom spells and graphics to game override

PRINT @11 // ~Installing spells and graphics...~

COPY ~luxleysoa/spells/copy~ ~override~

// Dark Rage
COPY ~luxleysoa/spells/fhlrage.spl~ ~override~
	SAY NAME1 @12
	SAY NAME2 @12

// Installing NPC portraits

COPY ~luxleysoa/portraits/FHSEBM.bmp~ ~override~
COPY ~luxleysoa/portraits/FHSEBS.bmp~ ~override~
COPY ~luxleysoa/portraits/FHANDREM.bmp~ ~override~
COPY ~luxleysoa/portraits/FHANDRES.bmp~ ~override~

COPY ~luxleysoa/bam~ ~override~

// Copying audio to override

PRINT @21 // ~Installing audio files...~

COPY ~luxleysoa/song/fhlblank.mus~ ~music~
COPY ~luxleysoa/song/fhlmu1.mus~ ~music~
COPY ~luxleysoa/song/fhlmu2.mus~ ~music~
COPY_EXISTING ~songlist.2da~ ~override~
SET_2DA_ENTRY 0 2 3 ~fhlblank.mus~
ADD_MUSIC  ~Luxley1~    ~music/fhlmu1.mus~
ADD_MUSIC  ~Luxley2~    ~music/fhlmu2.mus~

COPY ~luxleysoa/audio~ ~override~

// Copying and adding notes for areas

PRINT @31 // ~Installing area files...~

COPY ~luxleysoa/areas~ ~override~

COPY ~luxleysoa/areas/fh4800.are~ ~override~
	ADD_MAP_NOTE #3041 #330  ~gray~ @32 // ~The Main House~
	ADD_MAP_NOTE #3001 #2555 ~gray~ @33 // ~Training Ground~
	ADD_MAP_NOTE #1579 #2416 ~gray~ @34 // ~Lealia's Home~
	ADD_MAP_NOTE #365  #2667 ~gray~ @35 // ~Way Out~

// Compiling scripts and dialogues

PRINT @41 // ~Compiling dialogues and scripts...~

COMPILE ~luxleysoa/dialogues~
        ~luxleysoa/script~

EXTEND_BOTTOM ~ar0319.bcs~  ~luxleysoa/script/fhl0319.baf~
EXTEND_BOTTOM ~ar0400.bcs~  ~luxleysoa/script/fhl0400.baf~
EXTEND_BOTTOM ~ar0500.bcs~  ~luxleysoa/script/fhl0500.baf~
EXTEND_BOTTOM ~ar0513.bcs~  ~luxleysoa/script/fhl0513.baf~
EXTEND_BOTTOM ~ar0700.bcs~  ~luxleysoa/script/fhl0700.baf~
EXTEND_BOTTOM ~ar0810.bcs~  ~luxleysoa/script/fhl0810.baf~
EXTEND_BOTTOM ~baldur.bcs~  ~luxleysoa/script/fhlbaldur.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~aerie.bcs~   ~luxleysoa/script/fhlaer.baf~
EXTEND_BOTTOM ~anomen.bcs~  ~luxleysoa/script/fhlano.baf~
EXTEND_BOTTOM ~jaheira.bcs~ ~luxleysoa/script/fhljah.baf~
EXTEND_BOTTOM ~viconia.bcs~ ~luxleysoa/script/fhlvic.baf~

// Copying and patching items, their names and their descriptions

PRINT @51 // ~Installing custom items...~

// Sebastian's Book
COPY ~luxleysoa/items/fhlbook.itm~ ~override~
	SAY NAME1 @52
	SAY NAME2 @52
	SAY DESC @53

COPY ~luxleysoa/items/fhlbk2.itm~ ~override~
	SAY NAME1 @52
	SAY NAME2 @52
	SAY DESC @54

// Mietta
COPY ~luxleysoa/items/fhltig.itm~ ~override~
	SAY NAME1 @55
	SAY NAME2 @55
	SAY DESC @56

// Note
COPY ~luxleysoa/items/fhlnote.itm~ ~override~
	SAY NAME1 @57
	SAY NAME2 @57
	SAY DESC @58

// Old sword
COPY ~luxleysoa/items/fhlsw.itm~ ~override~
	SAY NAME1 @59
	SAY NAME2 @59
	SAY DESC @60

// Aegelfred's Chronicles
COPY ~luxleysoa/items/fhlchr.itm~ ~override~
	SAY NAME1 @61
	SAY NAME2 @61
	SAY DESC @62


// Adding Sebastian's custom Playwright kit - if the 2da isn't already there

// Adding custom kit...

ACTION_IF NOT FILE_EXISTS_IN_GAME ~override/fhlplay.fh~ BEGIN // add playwright kit

	COPY ~luxleysoa/2da/fhlplay.2da~ ~override~

	INCLUDE ~luxleysoa/lib/fhlplay.tph~

END


PRINT @81 // ~Installing creature files...~

//Copying creature files to override, adding kit to Sebastian's and adding their items

// Sebastian
COPY ~luxleysoa/cre/fhlseb08.cre~ ~override~
	SAY NAME1 @82
	SAY NAME2 @82
WRITE_SHORT 0x244 0
WRITE_BYTE 0x246 ~%FHLPLAY%~
WRITE_BYTE 0x247 0x40
	SAY INITIAL_MEETING   ~~
	SAY MORALE            @84  // ~There's nothing cowardly about self-preservation!~ [FHLSS1]
	SAY HAPPY             @85  // ~Oh, I knew I'd have good times with you.~ [FHLSS2]
	SAY UNHAPPY_ANNOYED   @86  // ~I'm older and wiser than you, so why aren't we doing what I want?~ [FHLSS4]
	SAY UNHAPPY_SERIOUS   @87  // ~I'll name no names, but someone in this group needs a kick in the face...~ [FHLSS5]
	SAY UNHAPPY_BREAKING  @88  // ~I don't owe you anything. I'm off.~ [FHLSS6]
	SAY LEADER            @89  // ~All will submit to me!~ [FHLSS7]
	SAY TIRED             @90  // ~I insist we stop. My feet are killing me.~ [FHLSS8]
	SAY BORED             @91  // ~There are so many better things we could be doing. Shall I show you some?~ [FHLSS9]
	SAY BATTLE_CRY1       @92  // ~I'm sure this can be sorted out amicably!~ [FHLSS10]
	SAY BATTLE_CRY2       @93  // ~What are you waiting for? Attack them!~ [FHLSS11]
	SAY BATTLE_CRY3       @94  // ~You there! You look tense! How about a massage?~ [FHLSS12]
	SAY BATTLE_CRY4       @95  // ~Hit 'em in the groin, hit 'em in the knee, hit 'em in the eye so they can't see!~ [FHLSS13]
	SAY BATTLE_CRY5       @96  // ~You fight, I'll, er, guard the packs!~ [FHLSS14]
	SAY DAMAGE            @97  // ~~ [FHLSS15]
	SAY DYING             @98  // ~~ [FHLSS16]
	SAY HURT              @99  // ~Ohh, I'm going to have to wash that out...~ [FHLSS17]
	SAY AREA_FOREST       @100 // ~What a charming setting for a play. Now, where could I find some nymphs?~ [FHLSS18]
	SAY AREA_CITY         @101 // ~Don't worry, I can protect you from the perils of the big city.~ [FHLSS19]
	SAY AREA_DUNGEON      @102 // ~My, you have excellent taste in places to visit. What next? A dank hole? Oh, wait...~ [FHLSS20]
	SAY AREA_DAY          @103 // ~Do we have to adventure today? Can't we just, you know, amuse ourselves?~ [FHLSS21]
	SAY AREA_NIGHT        @104 // ~Ahh, the sky's so clear, the air's so pure, the stars are plentiful.~ [FHLSS22]
	SAY SELECT_COMMON1    @105 // ~Yes?~ [FHLSS23]
	SAY SELECT_COMMON2    @106 // ~At your service.~ [FHLSS24]
	SAY SELECT_COMMON3    @107 // ~Oh, ask someone else.~ [FHLSS25]
	SAY SELECT_COMMON4    @108 // ~I hope you're not about to order me around.~ [FHLSS26]
	SAY SELECT_COMMON5    @109 // ~Can it wait?~ [FHLSS27]
	SAY SELECT_COMMON6    @110 // ~What's wrong with you?~ [FHLSS28]
	SAY SELECT_ACTION1    @111 // ~If I must.~ [FHLSS29]
	SAY SELECT_ACTION2    @112 // ~With pleasure.~ [FHLSS30]
	SAY SELECT_ACTION3    @113 // ~I'm sure you'd do it better.~ [FHLSS31]
	SAY SELECT_ACTION4    @114 // ~Anything for you.~ [FHLSS32]
	SAY SELECT_ACTION5    @115 // ~Only if I get my reward.~ [FHLSS33]
	SAY SELECT_ACTION6    @116 // ~I'd better enjoy this.~ [FHLSS34]
	SAY SELECT_ACTION7    @117 // ~This isn't going to be boring, is it?~ [FHLSS35]
	SAY SELECT_RARE1      @118 // ~Hang on, I'm halfway through a stanza.~ [FHLSS36]
	SAY SELECT_RARE2      @119 // ~Would you like Uncle Sebastian to get you some candy? Maybe then I'll get some peace.~ [FHLSS37]
	SAY CRITICAL_HIT      @120 // ~Did you see that?!~ [FHLSS38]
	SAY CRITICAL_MISS     @121 // ~Meant to do it!~ [FHLSS39]
	SAY TARGET_IMMUNE     @122 // ~I may as well read a book instead.~ [FHLSS40]
	SAY INVENTORY_FULL    @123 // ~I'm not a mule.~ [FHLSS41]
	SAY PICKED_POCKET     @124 // ~Ooh, pretty things for me. I mean...for all of us.~ [FHLSS42]
	SAY HIDDEN_IN_SHADOWS @125 // ~Boo!~ [FHLSS43]
	SAY SPELL_DISRUPTED   @126 // ~I didn't want to cast that one anyway.~ [FHLSS44]
	SAY SET_A_TRAP        @113 // ~I'm sure you'd do it better.~ [FHLSS31]
	SAY BIO               @127 // ~It is fair to say that whenever you question SEBASTIAN about himself he is maddeningly elusive. He is a playwright by trade - or so he says, though he is secretive about his work and claims that a great deal of what he writes would go over your head. He has a keen sense of frivolity and seems to take little in life with any seriousness. Nevertheless, on occasion it appears that there is something else going on with him, and it would be unwise to underestimate his intelligence.~
	WRITE_ASCII 0x248 ~FHLSEB~ #8  // override
	WRITE_ASCII 0x2cc ~FHLSEB~ #8  // dialogue
	WRITE_ASCII 0x280 ~FHLSEB~ #32 // DV
	WRITE_ASCII 0x34  ~FHSEBS~ #8  // small portrait
	WRITE_ASCII 0x3c  ~FHSEBM~ #8  // big portrait
	ADD_CRE_ITEM ~STAF01~ #0 #0 #0 ~IDENTIFIED~ ~WEAPON1~
	ADD_CRE_ITEM ~FHLBOOK~ #0 #0 #0 ~IDENTIFIED&UNDROPPABLE~ ~INV1~
	ADD_CRE_ITEM ~POTN52~ #3 #0 #0 ~IDENTIFIED~ ~INV2~
BUT_ONLY

SCRIPT_OVERRIDE 0x248
SCRIPT_CLASS 0x250
SCRIPT_RACE 0x258
SCRIPT_GENERAL 0x260
SCRIPT_DEFAULT 0x268
DEATHVAR 0x280
DIALOG 0x2cc

// Andrei
COPY ~luxleysoa/cre/fhland07.cre~ ~override~
     ~luxleysoa/cre/fhland09.cre~ ~override~
     ~luxleysoa/cre/fhland11.cre~ ~override~
     ~luxleysoa/cre/fhland13.cre~ ~override~
	SAY NAME1 @130
	SAY NAME2 @130
	SAY MORALE            @131 // ~I don't want-- I should go back!~ [FHLASS1]
	SAY HAPPY             @132 // ~Xavier would be proud of what we're doing.~ [FHLASS2]
	SAY UNHAPPY_ANNOYED   @133 // ~What are you doing?~ [FHLASS3]
	SAY UNHAPPY_SERIOUS   @134 // ~I don't know what you think you're doing, but this isn't right.~ [FHLASS4]
	SAY UNHAPPY_BREAKING  @135 // ~Look, that's it.~ [FHLASS5]
	SAY LEADER            @136 // ~I'll do my best to live up to your expectations.~ [FHLASS6]
	SAY TIRED             @137 // ~I don't think it's a good idea for us to get too tired.~ [FHLASS7]
	SAY BORED             @138 // ~I'd rather be in the estate.~ [FHLASS8]
	SAY BATTLE_CRY1       @139 // ~Hyah!~ [FHLASS9]
	SAY BATTLE_CRY2       @140 // ~Die!~ [FHLASS10]
	SAY BATTLE_CRY3       @141 // ~To the death!~ [FHLASS11]
	SAY BATTLE_CRY4       @142 // ~Take that!~ [FHLASS12]
	SAY BATTLE_CRY5       @143 // ~Attack!~ [FHLASS13]
	SAY DAMAGE            @144 // ~~ [FHLASS14]
	SAY DYING             @145 // ~Uh - I wish I could--~ [FHLASS15]
	SAY HURT              @146 // ~I need some healing, quickly!~ [FHLASS16]
	SAY AREA_FOREST       @147 // ~Er... you have got a map, haven't you?~ [FHLASS17]
	SAY AREA_CITY         @148 // ~I never thought I'd see so many people...~ [FHLASS18]
	SAY AREA_DUNGEON      @149 // ~Don't worry, I'm watching your back.~ [FHLASS19]
	SAY AREA_DAY          @150 // ~The sunshine always looks so bright at home.~ [FHLASS20]
	SAY AREA_NIGHT        @151 // ~Are we going to sleep anytime soon?~ [FHLASS21]
SAY SELECT_COMMON1    @152 // ~~ [FHLASS22]
	SAY SELECT_COMMON2    @153 // ~Hmm?~ [FHLASS23]
	SAY SELECT_COMMON3    @154 // ~What is it?~ [FHLASS24]
	SAY SELECT_COMMON4    @155 // ~Do you need anything?~ [FHLASS25]
	SAY SELECT_COMMON5    @156 // ~What?~ [FHLASS26]
	SAY SELECT_COMMON6    @157 // ~What do you need?~ [FHLASS27]
	SAY SELECT_ACTION1    @158 // ~All right.~ [FHLASS28]
	SAY SELECT_ACTION2    @159 // ~Of course.~ [FHLASS29]
	SAY SELECT_ACTION3    @160 // ~Whatever you say.~ [FHLASS30]
	SAY SELECT_ACTION4    @161 // ~If it helps.~ [FHLASS31]
	SAY SELECT_ACTION5    @162 // ~Sure.~ [FHLASS32]
	SAY SELECT_ACTION6    @163 // ~If that's what you want.~ [FHLASS33]
	SAY SELECT_ACTION7    @164 // ~If you say so.~ [FHLASS34]
	SAY SELECT_RARE1      @165 // ~Andrei Turi Xavier Luxley, at your service.~ [FHLASS35]
	SAY SELECT_RARE2      @166 // ~As eventful as all this is, I do miss the estate.~ [FHLASS36]
	SAY CRITICAL_HIT      @167 // ~Ha!~ [FHLASS37]
	SAY CRITICAL_MISS     @168 // ~Dammit!~ [FHLASS38]
	SAY TARGET_IMMUNE     @169 // ~I can't seem to do anything!~ [FHLASS39]
	SAY INVENTORY_FULL    @170 // ~I can't carry all of that.~ [FHLASS40]
	SAY PICKED_POCKET     ~~
	SAY HIDDEN_IN_SHADOWS @171 // ~Maybe I should get a hood.~ [FHLASS41]
	SAY SPELL_DISRUPTED   @172 // ~Ah, dammit!~ [FHLASS42]
	SAY SET_A_TRAP        ~~
	SAY BIO               @173 // ~ANDREI smiles when you ask him about himself. Though he is willing to talk about his relatives and is forthright about his beliefs, he is politely evasive on some subjects. He is skilled in hand-to-hand combat, a skill he developed at a young age, and was trained by an older member of his family. Despite his combat expertise, Andrei has only just left the family estate and seems a little naive about certain aspects of everyday life that you, perhaps, take for granted. Nevertheless, he comes across as quietly confident and it is rare to see him stray from a path he has chosen.~
	ADD_CRE_ITEM ~AMUL14~ #0 #0 #0 ~IDENTIFIED~ ~AMULET~
	ADD_CRE_ITEM ~POTN52~ #2 #0 #0 ~IDENTIFIED~ ~INV1~
WRITE_ASCII 0x248 ~FHLAND~ #8 // override
WRITE_ASCII 0x2cc ~FHLAND~ #8 // dialogue
WRITE_ASCII 0x280 ~FHLAND~ #32 //DV
WRITE_ASCII 0x34 ~FHANDRES~ #8 //small portrait
WRITE_ASCII 0x3c ~FHANDREM~ #8 //big portrait

SAY SELECT_COMMON1 ~~
SAY SELECT_COMMON1 @114
SAY SELECT_COMMON1 ~Yes?~ [FHLASS22]

COPY ~luxleysoa/cre/fhlbear.cre~ ~override~
	SAY NAME1 @130
	SAY NAME2 @130

COPY ~luxleysoa/cre/fhlcat.cre~ ~override~
	SAY NAME1 @82
	SAY NAME2 @82

//Copying non-joinable characters to game override

// Alexandra
COPY ~luxleysoa/cre/fhlal.cre~ ~override~
	SAY NAME1 @181
	SAY NAME2 @181
	ADD_CRE_ITEM ~HELMNOAN~ #0 #0 #0 ~NONE~ ~HELMET~
	ADD_CRE_ITEM ~CLCK13~ #0 #0 #0 ~NONE~ ~ARMOR~
	ADD_CRE_ITEM ~BRAC02~ #0 #0 #0 ~NONE~ ~GLOVES~
	ADD_CRE_ITEM ~POTN52~ #4 #0 #0 ~NONE~ ~INV1~
	ADD_CRE_ITEM ~WAND10~ #0 #0 #0 ~NONE~ ~INV2~
	ADD_CRE_ITEM ~SCRL71~ #0 #0 #0 ~NONE~ ~INV5~
	ADD_CRE_ITEM ~RNDTRE04~ #0 #0 #0 ~NONE~ ~INV6~
	ADD_CRE_ITEM ~RNDTRE05~ #0 #0 #0 ~NONE~ ~INV7~

// Alyssia
COPY ~luxleysoa/cre/fhlali.cre~ ~override~
	SAY NAME1 @182
	SAY NAME2 @182

// Archie
COPY ~luxleysoa/cre/fhlarch.cre~ ~override~
	SAY NAME1 @183
	SAY NAME2 @183

// Robin
COPY ~luxleysoa/cre/fhlboy.cre~ ~override~
	SAY NAME1 @184
	SAY NAME2 @184

// Thomas
COPY ~luxleysoa/cre/fhlboy2.cre~ ~override~
	SAY NAME1 @185
	SAY NAME2 @185

// Boy
COPY ~luxleysoa/cre/fhlboy3.cre~ ~override~
	SAY NAME1 @186
	SAY NAME2 @186

// Brid
COPY ~luxleysoa/cre/fhlbrid.cre~ ~override~
	SAY NAME1 @187
	SAY NAME2 @187
//	ADD_CRE_ITEM ~RNTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~
	ADD_CRE_ITEM ~RNDTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~

// Edward
COPY ~luxleysoa/cre/fhlchick.cre~ ~override~
	SAY NAME1 @188
	SAY NAME2 @188

// Mugger
COPY ~luxleysoa/cre/fhlcrim1.cre~ ~override~
	SAY NAME1 @189
	SAY NAME2 @189

// Durydil
COPY ~luxleysoa/cre/fhldu.cre~ ~override~
	SAY NAME1 @190
	SAY NAME2 @190

// Commoner
COPY ~luxleysoa/cre/fhlfred.cre~ ~override~
	SAY NAME1 @191
	SAY NAME2 @191

// Genevieve
COPY ~luxleysoa/cre/fhlgen.cre~ ~override~
	SAY NAME1 @192
	SAY NAME2 @192
	SAY SELECT_COMMON1 @193 // ~Hello, there.~ [FHLG4]

// Clara
COPY ~luxleysoa/cre/fhlgirl.cre~ ~override~
	SAY NAME1 @194
	SAY NAME2 @194

// Lianne
COPY ~luxleysoa/cre/fhlgirl2.cre~ ~override~
	SAY NAME1 @195
	SAY NAME2 @19

// Josefyne
COPY ~luxleysoa/cre/fhljos.cre~ ~override~
	SAY NAME1 @196
	SAY NAME2 @196
	ADD_CRE_ITEM ~STAF18~ #0 #0 #0 ~NONE~ ~WEAPON1~
	ADD_CRE_ITEM ~HELMNOAN~ #0 #0 #0 ~NONE~ ~HELMET~
	ADD_CRE_ITEM ~POTN52~ #2 #0 #0 ~IDENTIFIED~ ~QITEM1~
	ADD_CRE_ITEM ~SCRL71~ #0 #0 #0 ~IDENTIFIED~ ~INV5~
	ADD_CRE_ITEM ~RNDTRE04~ #0 #0 #0 ~NONE~ ~INV6~
	ADD_CRE_ITEM ~RNDTRE05~ #0 #0 #0 ~NONE~ ~INV7~
	ADD_CRE_ITEM ~MINHP1~ #0 #0 #0 ~NONE~ ~AMULET~

// Kavyn
COPY ~luxleysoa/cre/fhlkav.cre~ ~override~
	SAY NAME1 @197
	SAY NAME2 @19

// Lealia
COPY ~luxleysoa/cre/fhlleal.cre~ ~override~
	SAY NAME1 @198
	SAY NAME2 @198
	SAY SELECT_COMMON1 @199 // ~Hello, there. Is there anything you need?~ [FHLLEA6]
	ADD_CRE_ITEM ~CHAN01~ #0 #0 #0 ~NONE~ ~ARMOR~
	ADD_CRE_ITEM ~POTN52~ #3 #0 #0 ~NONE~ ~QITEM1~
	ADD_CRE_ITEM ~BLUN03~ #0 #0 #0 ~NONE~ ~WEAPON1~
	ADD_CRE_ITEM ~SHLD04~ #0 #0 #0 ~NONE~ ~SHIELD~

// Lucas
COPY ~luxleysoa/cre/fhlluc.cre~ ~override~
	SAY NAME1 @200
	SAY NAME2 @200
	SAY SELECT_COMMON1 @201 // ~What do you think you're looking at?~ [FHLLUC3]
	ADD_CRE_ITEM ~POTN52~ #3 #0 #0 ~NONE~ ~INV1~
	ADD_CRE_ITEM ~POTN11~ #0 #0 #0 ~NONE~ ~INV2~
	ADD_CRE_ITEM ~RNDTRE02~ #0 #0 #0 ~NONE~ ~INV6~

// Lyel
COPY ~luxleysoa/cre/fhllyel.cre~ ~override~
	SAY NAME1 @202
	SAY NAME2 @202
	ADD_CRE_ITEM ~CHAN05~ #0 #0 #0 ~NONE~ ~ARMOR~

COPY ~luxleysoa/cre/fhllyel2.cre~ ~override~
	SAY NAME1 @202
	SAY NAME2 @202
	ADD_CRE_ITEM ~CHAN05~ #0 #0 #0 ~NONE~ ~ARMOR~
	ADD_CRE_ITEM ~SHLD04~ #0 #0 #0 ~NONE~ ~SHIELD~
	ADD_CRE_ITEM ~SW1H14~ #0 #0 #0 ~NONE~ ~WEAPON1~

// Alistair
COPY ~luxleysoa/cre/fhlm1.cre~ ~override~
	SAY NAME1 @203
	SAY NAME2 @203
//	ADD_CRE_ITEM ~RNTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~
	ADD_CRE_ITEM ~RNDTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~

// Lantro
COPY ~luxleysoa/cre/fhlm2.cre~ ~override~
	SAY NAME1 @204
	SAY NAME2 @204
//	ADD_CRE_ITEM ~RNTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~
	ADD_CRE_ITEM ~RNDTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~

// Jonathen
COPY ~luxleysoa/cre/fhlm3.cre~ ~override~
	SAY NAME1 @205
	SAY NAME2 @205
//	ADD_CRE_ITEM ~RNTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~
	ADD_CRE_ITEM ~RNDTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~

// Katrin
COPY ~luxleysoa/cre/fhlm4.cre~ ~override~
	SAY NAME1 @205
	SAY NAME2 @206
//	ADD_CRE_ITEM ~RNTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~
	ADD_CRE_ITEM ~RNDTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~

// Nicolai
COPY ~luxleysoa/cre/fhlm5.cre~ ~override~
	SAY NAME1 @207
	SAY NAME2 @207
//	ADD_CRE_ITEM ~RNTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~
	ADD_CRE_ITEM ~RNDTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~

// Farris
COPY ~luxleysoa/cre/fhlm6.cre~ ~override~
	SAY NAME1 @208
	SAY NAME2 @208
//	ADD_CRE_ITEM ~RNTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~
	ADD_CRE_ITEM ~RNDTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~

// Tiger
COPY ~luxleysoa/cre/fhlmie1.cre~ ~override~
	SAY NAME1 @209
	SAY NAME2 @209

// Mietta
COPY ~luxleysoa/cre/fhlmiet.cre~ ~override~
	SAY NAME1 @55
	SAY NAME2 @55

// Miles
COPY ~luxleysoa/cre/fhlmil.cre~ ~override~
	SAY NAME1 @210
	SAY NAME2 @210

// Katya
COPY ~luxleysoa/cre/fhlmw.cre~ ~override~
	SAY NAME1 @211
	SAY NAME2 @211

// Nari
COPY ~luxleysoa/cre/fhlngrl.cre~ ~override~
	SAY NAME1 @212
	SAY NAME2 @212

// Quennell
COPY ~luxleysoa/cre/fhlquen.cre~ ~override~
	SAY NAME1 @213
	SAY NAME2 @213
	ADD_CRE_ITEM ~FHLCHR~ #0 #0 #0 ~NONE~ ~INV6~

// Rosanna
COPY ~luxleysoa/cre/fhlros.cre~ ~override~
	SAY NAME1 @214
	SAY NAME2 @214
	SAY SELECT_COMMON1 @215 // ~Hello again.~ [FHLROS5]
	ADD_CRE_ITEM ~RNDTRE02~ #0 #0 #0 ~NONE~ ~INV6~
	ADD_CRE_ITEM ~POTN52~ #3 #0 #0 ~NONE~ ~INV1~
	ADD_CRE_ITEM ~POTN11~ #0 #0 #0 ~NONE~ ~INV2~

// Samuel
COPY ~luxleysoa/cre/fhlsam.cre~ ~override~
	SAY NAME1 @216
	SAY NAME2 @216
	SAY SELECT_COMMON1 @217 // ~Hello again.~ [FHLSAM2]
	ADD_CRE_ITEM ~PLAT04~ #0 #0 #0 ~IDENTIFIED~ ~ARMOR~
	ADD_CRE_ITEM ~SHLD05~ #0 #0 #0 ~IDENTIFIED~ ~SHIELD~
	ADD_CRE_ITEM ~HAMM03~ #0 #0 #0 ~IDENTIFIED~ ~WEAPON1~

// Simeon
COPY ~luxleysoa/cre/fhlsim.cre~ ~override~
	SAY NAME1 @218
	SAY NAME2 @218
	ADD_CRE_ITEM ~MFIST5~ #0 #0 #0 ~NONE~ ~WEAPON1~
	ADD_CRE_ITEM ~POTN52~ #3 #0 #0 ~NONE~ ~INV1~
	ADD_CRE_ITEM ~POTN11~ #0 #0 #0 ~NONE~ ~INV2~
	ADD_CRE_ITEM ~RNDTRE02~ #0 #0 #0 ~NONE~ ~INV6~

// Skeleton Warrior
COPY ~luxleysoa/cre/fhlskl1.cre~ ~override~
     ~luxleysoa/cre/fhlskl2.cre~ ~override~
	SAY NAME1 @219
	SAY NAME2 @219

// Turi
COPY ~luxleysoa/cre/fhlturi.cre~ ~override~
	SAY NAME1 @220
	SAY NAME2 @220
//	ADD_CRE_ITEM ~RNTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~
	ADD_CRE_ITEM ~RNDTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~

// Katryna
COPY ~luxleysoa/cre/fhlw1.cre~ ~override~
	SAY NAME1 @221
	SAY NAME2 @221
	ADD_CRE_ITEM ~LEAT02~ #0 #0 #0 ~NONE~ ~ARMOR~
	ADD_CRE_ITEM ~RNDTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~

// Siri
COPY ~luxleysoa/cre/fhlw2.cre~ ~override~
	SAY NAME1 @222
	SAY NAME2 @222
	ADD_CRE_ITEM ~CHAN01~ #0 #0 #0 ~NONE~ ~ARMOR~
	ADD_CRE_ITEM ~RNDTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~

// Danica
COPY ~luxleysoa/cre/fhlw3.cre~ ~override~
	SAY NAME1 @223
	SAY NAME2 @223
	ADD_CRE_ITEM ~RNDTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~

// Erinne
COPY ~luxleysoa/cre/fhlw4.cre~ ~override~
	SAY NAME1 @224
	SAY NAME2 @224
	ADD_CRE_ITEM ~RNDTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~

// Serah
COPY ~luxleysoa/cre/fhlw5.cre~ ~override~
	SAY NAME1 @225
	SAY NAME2 @225
	ADD_CRE_ITEM ~RNDTRE01~ #0 #0 #0 ~NONE~ ~QITEM1~

// Xavier
COPY ~luxleysoa/cre/fhlxav.cre~ ~override~
	SAY NAME1 @226
	SAY NAME2 @226
	ADD_CRE_ITEM ~HELMNOAN~ #0 #0 #0 ~NONE~ ~HELMET~
	ADD_CRE_ITEM ~CLCK10~ #0 #0 #0 ~NONE~ ~ARMOR~
	ADD_CRE_ITEM ~RING06~ #0 #0 #0 ~NONE~ ~LRING~
	ADD_CRE_ITEM ~POTN52~ #4 #0 #0 ~IDENTIFIED~ ~QITEM1~
	ADD_CRE_ITEM ~RNDTRE04~ #0 #0 #0 ~NONE~ ~INV6~
	ADD_CRE_ITEM ~RNDTRE05~ #0 #0 #0 ~NONE~ ~INV7~


//Adding Sebastian and Andrei's dialogue files into the game

PRINT @231 // ~Adding dialogue files to the game...~

APPEND ~pdialog.2da~
~FHLSEB FHLSEBP FHLSEBJ FHLSEBD~
UNLESS ~FHLSEB~
UNLESS ~25POST~

APPEND ~pdialog.2da~
~FHLAND FHLANDP FHLANDJ FHLANDD~
UNLESS ~FHLAND~
UNLESS ~25POST~

APPEND ~interdia.2da~
~FHLSEB BFHLSEB~
UNLESS ~FHLSEB~
UNLESS ~25POST~

APPEND ~interdia.2da~
~FHLAND BFHLAND~
UNLESS ~FHLAND~
UNLESS ~25POST~

APPEND ~pdialog.2da~
~FHLSEB FHLSEBP FHLSEBJ FHLSEBD FHLS25P FHLS25J FHLS25D FHLS25~
UNLESS ~FHLSEB~
IF ~25POST~

APPEND ~pdialog.2da~
~FHLAND FHLANDP FHLANDJ FHLANDD FHLA25P FHLA25J FHLA25D FHLA25~
UNLESS ~FHLAND~
IF ~25POST~

APPEND ~interdia.2da~
~FHLSEB BFHLSEB BFHSEB25~
UNLESS ~FHLSEB~
IF ~25POST~

APPEND ~interdia.2da~
~FHLAND BFHLAND BFHLAND~
UNLESS ~FHLAND~
IF ~25POST~

//Adding the main area to the master area file

APPEND ~mastarea.2da~
~FH4800 value~

//Decoding the audio and unpacking the area files

AT_NOW ~luxleysoa/luxaudiotiz.bat~
PRINT ~The audio and area files for the Luxley Family mod have been unpacked to your computer.~
AT_UNINSTALL ~luxleysoa/luxuninstall.bat~
